package com.example.electrophy_app

data class ExperimentMode(
    val id: String,
    val name: String,
    val description: String,
    val icon: String,
    val category: String,
    // Sensor config
    val streamMode: GraphMode,
    val lowGOdr: String? = null,
    val highGOdr: String? = null,
    val gyroOdr: String? = null,
    val lowGRange: String? = null,
    val highGRange: String? = null,
    val gyroRange: String? = null,
    // Trigger config
    val autoTriggerEnabled: Boolean = false,
    val triggerAxis: String = "Z",
    val triggerCondition: String = "Deviation",
    val triggerThreshold: Float = 50f,
    val triggerDelayMs: Long = 200L,
    // UI config
    val timeWindowSec: Float = 5f,
    val filterEnabled: Boolean = false,
    val filterAlpha: Float = 0.2f,
    val chartTitle: String = "",
    val yAxisUnit: String = "",
    // Analysis features
    val showPeakForce: Boolean = false,
    val showImpulse: Boolean = false,
    val showPeriodDetection: Boolean = false,
    val showVelocityIntegration: Boolean = false,
    val showFreeFallDetection: Boolean = false,
    val is3dAirplaneMode: Boolean = false,
    val instructions: String = ""
)

val experimentModes: List<ExperimentMode> = listOf(
    // 1. Flight & Aerodynamics
    ExperimentMode(
        id = "airplane_3d",
        name = "3D Aeroplane Attitude",
        description = "Interactive 3D airplane model synced with sensor Pitch, Roll & Yaw with HUD.",
        icon = "✈️",
        category = "Flight & Aerodynamics",
        streamMode = GraphMode.ALL,
        lowGOdr = "120hz",
        gyroOdr = "120hz",
        lowGRange = "4g",
        gyroRange = "2000dps",
        timeWindowSec = 5f,
        filterEnabled = true,
        filterAlpha = 0.25f,
        chartTitle = "Orientation Telemetry",
        yAxisUnit = "deg",
        is3dAirplaneMode = true,
        instructions = "1. Hold the sensor board horizontally (facing forward like an aircraft fuselage)\n2. Tap 'Zero Heading' to calibrate your forward direction\n3. Tilt up/down for Pitch (Climb & Dive)\n4. Tilt left/right for Roll (Banking)\n5. Turn left/right horizontally for Yaw (Heading)\n6. Watch the 3D aircraft model & artificial horizon HUD react in real time!"
    ),

    // 2. Kinematics
    ExperimentMode(
        id = "pendulum",
        name = "Simple Pendulum",
        description = "Measure oscillation period of a pendulum.",
        icon = "📐",
        category = "Kinematics",
        streamMode = GraphMode.LOW_G,
        lowGOdr = "120hz",
        lowGRange = "4g",
        autoTriggerEnabled = false,
        timeWindowSec = 10f,
        filterEnabled = true,
        filterAlpha = 0.5f,
        chartTitle = "Pendulum Oscillation",
        yAxisUnit = "mg",
        showPeriodDetection = true,
        instructions = "1. Attach the sensor to a pendulum bob\n2. Tap Resume to start streaming\n3. Set the pendulum swinging\n4. Observe the periodic acceleration pattern\n5. The detected period T can verify T=2π√(L/g)"
    ),
    ExperimentMode(
        id = "vehicle_accel",
        name = "Vehicle Acceleration",
        description = "Estimate velocity change by integrating acceleration.",
        icon = "🏎️",
        category = "Kinematics",
        streamMode = GraphMode.LOW_G,
        lowGOdr = "120hz",
        lowGRange = "8g",
        autoTriggerEnabled = true,
        triggerAxis = "Z",
        triggerCondition = "Deviation",
        triggerThreshold = 3000f,
        triggerDelayMs = 500L,
        timeWindowSec = 30f,
        filterEnabled = true,
        filterAlpha = 0.1f,
        chartTitle = "Vehicle Acceleration",
        yAxisUnit = "mg",
        showVelocityIntegration = true,
        instructions = "1. Mount the sensor in a vehicle\n2. Tap Resume to start streaming\n3. Accelerate, cruise, and brake\n4. Observe the acceleration profile\n5. Velocity is estimated by integrating acceleration"
    ),

    // 3. Mechanics
    ExperimentMode(
        id = "newtons_third_law",
        name = "Newton's Third Law",
        description = "Measure peak impact force and impulse during a collision.",
        icon = "🥊",
        category = "Mechanics",
        streamMode = GraphMode.HIGH_G,
        highGOdr = "3840hz",
        highGRange = "320g",
        autoTriggerEnabled = true,
        triggerAxis = "Z",
        triggerCondition = "Deviation",
        triggerThreshold = 50f,
        triggerDelayMs = 200L,
        timeWindowSec = 1f,
        filterEnabled = false,
        chartTitle = "Impact Force",
        yAxisUnit = "g",
        showPeakForce = true,
        showImpulse = true,
        instructions = "1. Attach sensor to one of the colliding objects\n2. Tap Resume to start streaming\n3. Perform the collision — the auto-trigger will capture the impact\n4. Examine the peak force and impulse (∫F·dt) values\n5. Compare with the second object's sensor if available"
    ),
    ExperimentMode(
        id = "free_fall",
        name = "Free Fall",
        description = "Detect weightlessness and measure free fall duration.",
        icon = "⚖️",
        category = "Mechanics",
        streamMode = GraphMode.LOW_G,
        lowGOdr = "960hz",
        lowGRange = "2g",
        autoTriggerEnabled = true,
        triggerAxis = "Z",
        triggerCondition = "Below",
        triggerThreshold = 100f,
        triggerDelayMs = 500L,
        timeWindowSec = 3f,
        filterEnabled = true,
        filterAlpha = 0.3f,
        chartTitle = "Free Fall Detection",
        yAxisUnit = "mg",
        showFreeFallDetection = true,
        instructions = "1. Hold the device steady\n2. Tap Resume to start streaming\n3. Drop the device (onto a soft surface!)\n4. The sensor shows near-zero acceleration during free fall\n5. The auto-trigger captures the moment of weightlessness"
    ),
    ExperimentMode(
        id = "centripetal",
        name = "Centripetal Acceleration",
        description = "Measure steady inward acceleration during rotation.",
        icon = "🔄",
        category = "Mechanics",
        streamMode = GraphMode.LOW_G,
        lowGOdr = "480hz",
        lowGRange = "16g",
        autoTriggerEnabled = false,
        timeWindowSec = 5f,
        filterEnabled = false,
        chartTitle = "Centripetal Acceleration",
        yAxisUnit = "mg",
        showPeakForce = true,
        instructions = "1. Securely attach the sensor to a rotating object or string\n2. Tap Resume to start streaming\n3. Spin the object at a steady rate\n4. Observe the centripetal acceleration pattern\n5. Use the peak values with a=ω²r to verify"
    ),
    ExperimentMode(
        id = "impulse_momentum",
        name = "Impulse & Momentum",
        description = "Integrate force over time to find impulse.",
        icon = "💥",
        category = "Mechanics",
        streamMode = GraphMode.HIGH_G,
        highGOdr = "3840hz",
        highGRange = "256g",
        autoTriggerEnabled = true,
        triggerAxis = "Z",
        triggerCondition = "Deviation",
        triggerThreshold = 30f,
        triggerDelayMs = 200L,
        timeWindowSec = 1f,
        filterEnabled = false,
        chartTitle = "Impulse Measurement",
        yAxisUnit = "g",
        showPeakForce = true,
        showImpulse = true,
        instructions = "1. Attach sensor to the colliding object\n2. Tap Resume to start streaming\n3. Perform the collision\n4. The shaded area under the F-t curve shows impulse J=∫F·dt\n5. With known mass: Δv = J/m"
    ),
    ExperimentMode(
        id = "elevator",
        name = "Elevator Physics",
        description = "Measure apparent weight variations in an elevator.",
        icon = "🎢",
        category = "Mechanics",
        streamMode = GraphMode.LOW_G,
        lowGOdr = "60hz",
        lowGRange = "4g",
        autoTriggerEnabled = false,
        timeWindowSec = 30f,
        filterEnabled = true,
        filterAlpha = 0.15f,
        chartTitle = "Apparent Weight / g-Forces",
        yAxisUnit = "mg",
        instructions = "1. Hold the device in an elevator\n2. Tap Resume to start streaming\n3. Ride the elevator up and down\n4. Observe acceleration changes during start/stop\n5. The Z-axis shows apparent weight variations around 1g"
    )
)

fun getExperimentModeById(id: String): ExperimentMode? = experimentModes.find { it.id == id }
